version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypw
    networks:
      - symfony
    ports:
      - "3306:3306"
  sf-react:
    image: svg1007/sf-react
    container_name: sf-react
    external_links:
      - mysql
    networks:
      - symfony
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - symfony
    ports:
      - "80:80"

networks:
  symfony:
